FROM balenalib/%%RESIN_MACHINE_NAME%%-debian:stretch


RUN apt-get update && \
    apt-get install ouimeaux websockets asyncio socket && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /usr/src/app

COPY ./run.py ./run.py

EXPOSE 8765 8765

RUN ls
RUN pwd


CMD ["python", "Storage.py"]
